version: '3.7'

services:
  web:
    build: ./web
    container_name: taibif-web-dev-container
    image: taibif-web-dev-image
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/taibif-code
    command: python web/manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - web/.env
  db:
    container_name: taibif-db-container
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=taibif
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../taibif-volumes/pgdata:/var/lib/postgresql/data/pgdata
  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8080:8080