version: '3.7'

services:
  web:
    ports:
      - 8000:8000
  adminer:
    image: adminer
    restart: always
    links:
      - db:db
    ports:
      - 8080:8080
  db:
    ports:
      - 5432:5432
  